"""Public CHRONOS Phase 4.4 impact-synthesis API."""

from .builder import (
    synthesize_impact,
    synthesize_impact_from_artifacts,
    validate_impact_synthesis,
)
from .errors import (
    ImpactSynthesisEntryError,
    ImpactSynthesisError,
    ImpactSynthesisSerializationError,
    ImpactSynthesisValidationError,
)
from .models import (
    IMPACT_SYNTHESIS_SCHEMA_VERSION,
    BlockingQuestion,
    BlockingQuestionResolutionState,
    ChangeReviewAssessment,
    ContextHighlight,
    ContextHighlightKind,
    DecisionCertainty,
    DecisionDisposition,
    DecisionEvidence,
    DecisionEvidenceType,
    DecisionReason,
    DecisionReasonCode,
    DecisionRule,
    DecisionRuleInputs,
    DecisionRuleResult,
    ImpactSynthesis,
    ImpactSynthesisSummary,
    ImpactSynthesisValidationState,
    RepresentativeEvidencePath,
    RepresentativePathKind,
    RequiredEvidence,
    RequiredEvidenceState,
)
from .queries import (
    get_blocking_questions,
    get_change_assessment,
    get_context_highlights,
    get_decision_reasons,
    get_disposition,
    get_representative_paths,
    get_required_evidence,
    get_scope_summary,
)
from .rules import DEFAULT_DECISION_RULES, evaluate_decision
from .serialization import (
    export_impact_synthesis,
    impact_synthesis_from_json,
    impact_synthesis_semantic_fingerprint,
    impact_synthesis_to_dict,
    impact_synthesis_to_json,
    load_impact_synthesis,
)

__all__ = [
    "IMPACT_SYNTHESIS_SCHEMA_VERSION",
    "DEFAULT_DECISION_RULES",
    "BlockingQuestion",
    "BlockingQuestionResolutionState",
    "ChangeReviewAssessment",
    "ContextHighlight",
    "ContextHighlightKind",
    "DecisionCertainty",
    "DecisionDisposition",
    "DecisionEvidence",
    "DecisionEvidenceType",
    "DecisionReason",
    "DecisionReasonCode",
    "DecisionRule",
    "DecisionRuleInputs",
    "DecisionRuleResult",
    "ImpactSynthesis",
    "ImpactSynthesisEntryError",
    "ImpactSynthesisError",
    "ImpactSynthesisSerializationError",
    "ImpactSynthesisSummary",
    "ImpactSynthesisValidationError",
    "ImpactSynthesisValidationState",
    "RepresentativeEvidencePath",
    "RepresentativePathKind",
    "RequiredEvidence",
    "RequiredEvidenceState",
    "evaluate_decision",
    "export_impact_synthesis",
    "get_blocking_questions",
    "get_change_assessment",
    "get_context_highlights",
    "get_decision_reasons",
    "get_disposition",
    "get_representative_paths",
    "get_required_evidence",
    "get_scope_summary",
    "impact_synthesis_from_json",
    "impact_synthesis_semantic_fingerprint",
    "impact_synthesis_to_dict",
    "impact_synthesis_to_json",
    "load_impact_synthesis",
    "synthesize_impact",
    "synthesize_impact_from_artifacts",
    "validate_impact_synthesis",
]
